name: "Home Assistant Matter Hub (jeffothy)"
version: "main"
slug: "home-assistant-matter-hub-jeffothy"
description: "Development build from jeffothy fork"
url: "https://github.com/jeffothy/home-assistant-matter-hub"
panel_icon: mdi:chip
panel_title: Matter Hub
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
init: false
arch:
  - amd64
  - aarch64
  - armv7
image: "ghcr.io/jeffothy/home-assistant-matter-hub-addon"
ingress: true
ingress_port: 0
map:
  - addon_config:rw
options:
  app_log_level: info
  disable_log_colors: false
  mdns_network_interface: ""
schema:
  app_log_level: list(silly|debug|info|notice|warn|error|fatal)
  disable_log_colors: bool
  mdns_network_interface: "str?"
